### ISSUE TITLE
Update `rawplus.yaml` with quoted strings

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/clindata#32]
It turns out that quoting strings is important: 
The values below will all return `TRUE`
```yaml
Value1: Y
Value2: Yes
Value3: TRUE
```
Similarly: 
```
> read_yaml(text = 'N')
[1] FALSE
> read_yaml(text = '"N"')
[1] "N"
```
